### ISSUE TITLE
Guards Not Working With Strings

### ISSUE THREAD

**Issue by daniel-nagy** [jean343/styless#63]
```Less
& when (@variant = "secondary") {
  background-color: @btnSecondaryBgColor;
  border-color: @btnSecondaryBorderColor;
  color: @btnSecondaryColor;
}
```

This guard is always entered, even when `props.variant` is not equal to secondary.

**Comment by jean343** [comment]
Thanks for reporting this issue, I believe we have limited support for guards.
Could you add the complete example with the React component and I will try it.

Thanks,

**Comment by jean343** [comment]
A workaround is to use the styled syntax

```Less
${props => props.variant === "secondary" && css`
  background-color: @btnSecondaryBgColor;
  border-color: @btnSecondaryBorderColor;
  color: @btnSecondaryColor;
`}
```
